language: java
git:
  quiet: true
env:
  global:
    - secure: "5fxP+acq0UEnFuYpzpICrizfBKEIJBRtoleoNOEthb9NrlbxEIbNZ8TTq10EoEw2SXb+cg9GEo+MleEqrQkeTS6+4WSjd4RJkwLxjx0T6prlAoqapELII0t7lyNOG0iYCfTcXfBg+yHAOF5jvWiqFJe/+5+enZOTrpGM6Ub+gfLTBvWPDXstR/lRSZk/YGqndxUKbRJ23yTTrpBjTFL/GOcoclcc4I1WbCBwthKGzPCu2aK36A7l7cDzQxMiTs+j+pRc5NBsF5EcrgWl8isCFgyT4UmftGjRpY6GRp7afpL/b9Guf7tenCYs6GQ1/mHY6Bzi78N3Zmr3g4gzOR3uV/mz9k4SdZhhdMohcec0CEARnbvOME2RxXcxaRynlGL7Ge92Qyv5RpadA9WESPFl+OfntcgJ4oc6FaCOr8P93gEhu35xmMhqNkAbWo/5R5sBfQuGZ+SIEWigry0q7ZAC8EL1kG416cs3wdR0EXHbvQ4344UbHBOy5uQk4h8wbg9NiJlpV4b/AGdnh3enIr6D1BtO1nwEWN3kosMkEVnVgz0AhGPi2DkuLfFcEoEskjsdkrvO7EB4W5JTWCpM7wzJJx/97UGdaaHxfkVcAv5vTDhUghhNVNcsB7rcNeu8JrDyy40vB3lDlIzTLZyyJR6tROfaYWztJaN2gHJFZ5WVpUI="
branches:
  only:
    - master
    - /v\d+\.\d+[a-zA-Z-_]+?(\.\d+[a-zA-Z-_]+?)/
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ant dist
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: dE3wu/mj4290JbKl/9XV3HYVjufALDxQNjAfi0MWOq0ZAzZ+v2/bXj9q7w1dc3jNf50FLk4EWkG7yoW213tYVqcMrUHfr1p3Pm7qpGtDfNMAR9ZisUN3cx1HGXGCXQjA8tANV3rNeMw7YyS52WLZPg724T8HX4pDyyV2Swxw//gYzXNXelGjSMjt2v/1B3QnK66VnAiTzz/zXGv5rJgdu+7BOSLFOq05IpXf/MMUxh0rZ/VTJvV3UxrrcSs1uT0hUi6dAthQPg6uxisQuy+ZIXDJKuRZgbOTqdzrZlCq/V2lA+FNixyowAlko8cVh6V1f6uoG2P7L4QDQN3r/KBdql5pp1X+MB6tqiKkyUwOO6dzGk968Vsn2cU9VRpmqccai2gKUXTgfrvK7GS1JmxKsfWxSRKv/WXkGeD71ixKViRv0fIsgr4gBKHTPRHsbe3QMPW+R4fa2GlCdU0pG/BcFpFe/OTomeiQL+f5h+kwN7F4Nt52hi2+OddCDoVyC++sppEFq8GYgrJBpuFIe+XsqXacNs708qbK4wV7sFGctjQ4LDDh5xpIoiUvNLVt7amdlOaNk/++iM8Pj/pANCb0882LzkoasRFJNtrhdPDRkwKt82oEPJ6J9MQn9WUN3W8tgJ8KPn2/oQP7JkWORKH1C9zlXF6w1tA0uPIijWaAF80=
  file: MedTagger.zip
  on:
    tags: true
  skip_cleanup: true
